name: test

on:
  workflow_dispatch:
    branches: 
      - main

jobs:
  test:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repo
        uses: actions/checkout@v5
      
      - name: Setup python
        uses: actions/setup-python@v5
        with:
          python-version: "3.12"

      - name: Cache pip cache
        uses: actions/cache@v4
        with:
          path: ~/.cache/pip/.venv
          key: ${{ runner.os }}-pip-${{ hashFiles("gpttwo/requirements.txt") }}
          restore-keys:
            ${{ runner.os }}-pip-
      
      - name: Install requirements
        run: |
          python -m venv .venv
          source .venv/bin/activate
          pip install --upgrade pip
          pip install -r gpttwo/requirements.txt

      - name: Cache model
        uses: actions/cache@v4
        with:
          path: ~/.cache/huggingface
          key: ${{ runner.os }}-hug-${{ hashFiles("gpttwo/README.md") }}
          restore-keys:
            ${{ runner.os }}-hf-

      - name: Run
        run: |
          source .venv/bin/activate
          python gpttwo/gpttwo.py
